---
## Version-specific settings that override the values in cfg/config.yaml

master:
  components:
    - apiserver
    - scheduler
    - controllermanager
    - etcd
    - flanneld

  apiserver:
    bins:
      - kube-apiserver
    confs: 
      - /var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml
    defaultconf: /var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml

  scheduler:
    bins:
      - kube-scheduler
    confs:
      - /var/lib/rancher/rke2/agent/pod-manifests/kube-scheduler.yaml
    defaultconf: /var/lib/rancher/rke2/agent/pod-manifests/kube-scheduler.yaml

  controllermanager:
    bins:
      - kube-controller-manager
    confs:
      - /var/lib/rancher/rke2/agent/pod-manifests/kube-controller-manager.yaml
    defaultconf: /var/lib/rancher/rke2/agent/pod-manifests/kube-controller-manager.yaml
  
  etcd:
    bins:
      - etcd
    confs:
      - /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml
    defaultconf: /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml

  flanneld:
    optional: true
    bins:
      - flanneld
    defaultconf: /etc/sysconfig/flanneld

target_mapping:
  "rke2-cis-1.5":
    - "master"
    - "node"
    - "controlplane"
    - "etcd"
    - "policies"
